[package]
name = "golf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.9.1", features = ["bevy_sprite", "bevy_text", "wav"] }
bevy-inspector-egui = { version = "0.17.0", optional = true }
bevy_rapier2d = { version = "0.21.0", default-features = false, features = ["simd-nightly", "async-collider", "dim2"] }
bevy_tileset = "0.6.0"

[features]
default = ["native"]
debug_render = ["bevy_rapier2d/debug-render-2d"]
wasm = ["bevy_rapier2d/wasm-bindgen"]
native = ["bevy_rapier2d/parallel"]
inspector = ["bevy-inspector-egui"]
debug_assets = ["bevy/debug_asset_server"]