[package]
name = "golf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.9.1", features = ["bevy_sprite", "bevy_text", "wav"] }
bevy-inspector-egui = { version = "0.17.0", optional = true }
bevy_rapier2d = { version = "0.20.0", default-features = false, features = ["simd-nightly", "async-collider", "dim2"] }
bevy_tileset = "0.6.0"
postcard = { version = "1.0.4", features = ["use-std"] }
quick-xml = { version = "0.28.0", features = ["serialize"] }
serde = { version = "1.0.156", features = ["derive"] }
toml = "0.7.3"
xml-schema-derive = "0.2.0"
yaserde = { version = "0.8.0", features = ["yaserde_derive"] }
yaserde_derive = "0.8.0"

[features]
default = ["native"]
debug_render = ["bevy_rapier2d/debug-render-2d"]
wasm = ["bevy_rapier2d/wasm-bindgen"]
native = ["bevy_rapier2d/parallel"]
inspector = ["bevy-inspector-egui"]
debug_assets = ["bevy/debug_asset_server"]

[build-dependencies]
postcard = { version = "1.0.4", features = ["use-std"] }
serde = "1.0.156"
toml = "0.7.3"
